### ISSUE TITLE
Strip images just for egalleymaker

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_addons#103]
Add an addon that we can add to the egalleymaker deploy file, to strip out all images from the HTML file. This should run just after htmlmaker.

**Comment by ericawarren** [comment]
Do you mean actual images embedded in the Word file by mistake, or to remove all image callouts? I already have @macmillanpublishers/vba_utilities#11 to remove embedded image files ready to go (today?) with some other fixes once I get the doc protection checking done. Unless you'd prefer to handle this somewhere else.

**Comment by nelliemckesson** [comment]
@ericawarren I mean stripping out all image placeholders entirely, since there's no point in preserving the image placeholders in egalleys when they all just have the fallback FPO image and they seem to cause trouble.

**Comment by nelliemckesson** [comment]
Also note that part of this script will need to check to see if an image was in a standalone section, and if so, strip the parent section as well.
