### ISSUE TITLE
[js] Rework author newsletter link stuff to happen via js - epubmaker_preprocessing.rb

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_addons#127]
In getlinkAuthorInfo, setNewsletterAuthorLinks, and updateImprintandEisbnPlaceholders, rework so that any content replacements/conversions happen via JS as much as possible, to account for the unpredictability of how attributes will be arranged in parent elements.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

https://app.asana.com/0/142682204252343/142682204252343 ; was this task for a PR review for something that's been done now?
