### ISSUE TITLE
[js] Make HTML TOC content conversions via javascript - epubmaker_postprocessing.rb

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_addons#128]
In the _hideTOC_fixTPtext_ function, make the content instertions/conversions via javascript instead. Probably will need to be a stand-alone javascript file.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
https://github.com/macmillanpublishers/bookmaker_addons/pull/134

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
merged & tested!
