### ISSUE TITLE
[js] Clean up spanISBN tags via js - htmlmaker_postprocessing.rb

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_addons#129]
In the _fixISBNSpans_ method, do the text replacements via javascript instead.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
submitted a PR for Nellie:
https://github.com/macmillanpublishers/bookmaker_addons/pull/135

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
merged & re-tested!
