### ISSUE TITLE
[rb] Scan titlepage info more carefully - metadata_preprocessing.rb

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_addons#130]
In the _setAuthorInfo_, _setBookTitle_, and _setBookSubtitle_ methods, when scanning for titlepage info, make the scan more robust, so that it can catch results even if the element class _is not_ the first attribute. The subsequent gsubs will also need to be adjusted accordingly.

E.g., currently we scan for this regex:

```html
<p class="TitlepageAuthorNameau">.*?</
```

Instead scan for something along these lines:

```html
<p.+="TitlepageAuthorNameau".*>.*?</
```

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
submitted for review: https://github.com/macmillanpublishers/bookmaker_addons/pull/141

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
updated the PR with unit tests

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
Approved & deployed
