### ISSUE TITLE
[js] Remove header block for epubs - epubmaker_preprocessing.js

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_addons#133]
We will be adding a header block for all section and div.part elements in htmlmaker_js (see https://github.com/macmillanpublishers/htmlmaker_js/issues/18). We'll want to strip this out for EPUB files, to avoid any ereader weirdness.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

submitted PR for this: https://github.com/macmillanpublishers/bookmaker_addons/pull/153

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

approved & merged!
