### ISSUE TITLE
Editions have different imprints; provision for running bookmaker as either one

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker_addons#142]
This wacky file https://www.dropbox.com/s/fz168u3n7kh4pyk/9781250154842_MNU.docx?dl=0 has a print edition which is St Martin Griffin, and an ebook edition which is a Swerve title.

Laurie Henderson needed it to come out as Swerve, but both _metadata_preprocessing.rb_ and _bookmaker_titlepage.rb_ defaulted to the print edition.  

To override _metadata_preprocessing.rb_ I added a meta tag to the html for the imprint, but if this comes up again it would be useful to devise an easier way to choose an edition or specify an imprint for both _bookmaker_titlepage.rb_ and _metadata_preprocessing.rb_

Opening this as an issue in the covermaker repo as well.

**Comment by mattretzer** [comment]
Covermaker companion issue: 
https://github.com/macmillanpublishers/covermaker/issues/37

**Comment by nelliemckesson** [comment]
This is already resolved for bookmaker_addons--adding the meta element is the override handling. We'll add the same handling to covermaker/bookmaker-titlepage.rb.
