### ISSUE TITLE
[ss] Remove PageBreak followed by Section-Start

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_addons#150]
If a PageBreak para is followed by any Section-Start para, remove the PageBreak.

This should happen in htmlmaker_postprocessing.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Submitted PR: https://github.com/macmillanpublishers/bookmaker_addons/pull/152

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

made edits as per comments in PR review

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Approved, merged into sectionstartstaging branch
