### ISSUE TITLE
'Acknowledgements' h1 in epub is not getting linked back to toc (with htmlmaker_js)

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker_addons#156]
This looks like it needs to be added manually [here](https://github.com/macmillanpublishers/bookmaker_addons/blob/master/epubmaker_postprocessing.js), or maybe we could use a more generic selector instead of calling out individual section heads.

The reason the link is there in the xsl conversion is that the section type for the Acknowledgments is the more generic 'Preface', which _is_ selected in epubmaker_postprocessing.js for adding link back to TOC.

**Comment by mattretzer** [comment]
Example files (for testing the fix): 
https://www.dropbox.com/s/2zy8vlxpmu5zb9q/9781250058911_MNU_NEW.docx?dl=0
https://www.dropbox.com/s/obt7cr8hkkc7qwg/9780765395399_MNU.docx?dl=0

**Comment by mattretzer** [comment]
A Section-Conclusion's h1 is also not getting reverse-link to ncx in epub, from this manuscript:
https://www.dropbox.com/s/2zy8vlxpmu5zb9q/9781250058911_MNU_NEW.docx?dl=0
(for the Epilogue)

**Comment by mattretzer** [comment]
Also Section-Bibliography, see this manuscript:
https://www.dropbox.com/s/47uft1npssebtcz/9781250080554_MNU_NEW.docx?dl=0

**Comment by mattretzer** [comment]
Note: use a more general selector (section h1) and make sure the section is child of body or Part

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

This was resolved via https://github.com/macmillanpublishers/bookmaker_addons/pull/162
