### ISSUE TITLE
Link all section heads to TOC

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_addons#17]
Currently only chapter titles link back to the TOC. Revise to link all section heads to TOC. See line 20 in epubmaker_postprocessing.

**Comment by nelliemckesson** [comment]
Still needs some tweaking -- I think maybe frontmatter heads? See Tor.com / Runtime / 9780765389787, per the ebooks team: "The heading on p6 "Acknowledgements" is still not linked to the TOC."

**Comment by nelliemckesson** [comment]
Also link part heads to the TOC

**Comment by mattretzer** [comment]
We did this one & tested:)
