### ISSUE TITLE
Replace strip-spans.xsl with javascript

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_addons#18]
Recreate the strip-spans.xsl in javascript/node

**Comment by MacmillanWorkflows** [comment]
➤ Nellie McKesson commented:
This will be fixed at the same time as https://github.com/macmillanpublishers/bookmaker_addons/issues/120

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Looks like this was done as part of https://github.com/macmillanpublishers/bookmaker_addons/pull/131
