### ISSUE TITLE
Long-hyphenated string with special character is not getting handled properly

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker_addons#185]
As per in this string in [this doc](https://www.dropbox.com/s/irce60eei8goy97/9780765393258_MNU.docx?dl=0):

> "I’m in a my-best-friend-isbeing-
> exorcised-tonight-hopefully-before-the-guy-who
> -put-an-evil-assassin-spirit-inside-him-comes-back-tokill-
> us-all-and-we’ve-been-cut-off-by-our-only-lifeline
> kind of mood.”

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

[luigi.squillante](https://app.asana.com/0/419737034401624/list), please review this PR, this was my bookmaker troubleshooting for today.. by the time I pinned down what it was & gave the user good output it was patched.
https://github.com/macmillanpublishers/bookmaker_addons/pull/184

**Comment by MacmillanWorkflows** [comment]
➤ luigi.squillante commented:

approved

**Comment by mattretzer** [comment]
Merged & deployed patch, closing.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

merged, deployed.
