### ISSUE TITLE
Multiple author running heads being weird

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/bookmaker_addons#35]
User ran Bookmaker on Tuesday 11/10 in swerve_pod path with a manuscript that has two authors (and thus, two author lines on the title page). The resulting PDF has both author's names on the verso running head, separated by a comma and no spaces: 
[Claimed by the Mate_first pass.pdf](https://github.com/macmillanpublishers/bookmaker_addons/files/34361/Claimed.by.the.Mate_first.pass.pdf)

There were no errors reported in the log. 
This was before the DB connection was deployed for metadata (?)

To test if the DB connection would fix the issue, I ran the MS through Bookmaker again in the workflows_test path, and the resulting PDF has NO running heads or page numbers:
[9781250107640_POD.pdf](https://github.com/macmillanpublishers/bookmaker_addons/files/34362/9781250107640_POD.pdf)

The log returned with this one also had no errors:

`Fri 11/13/2015 15:34:33.26 `
`Warning: SXXP0005: The source document is in namespace http://schemas.microsoft.com/office/2006/xmlPackage, but none of the template rules match elements in this namespace`
`Warning: at xsl:stylesheet on line 7 column 40 of footnotes.xsl: Running an XSLT 1 stylesheet with an XSLT 2 processor`
`Warning: at xsl:stylesheet on line 7 column 40 of strip-toc.xsl: Running an XSLT 1 stylesheet with an XSLT 2 processor`
`Warning: at xsl:stylesheet on line 5 column 31 of parts.xsl: Running an XSLT 1 stylesheet with an XSLT 2 processor`
`Warning: at xsl:stylesheet on line 6 column 34 of headings.xsl: Running an XSLT 1 stylesheet with an XSLT 2 processor`
`Warning: at xsl:stylesheet on line 5 column 31 of inlines.xsl: Running an XSLT 1 stylesheet with an XSLT 2 processor`
`SELECT * FROM vw_wf_title WHERE EDITION_EAN = '9781250107640'`
`No DB record found; falling back to manuscript fields`
`SELECT * FROM vw_wf_title WHERE EDITION_EAN = '9781250107640'`
`No DB record found; falling back to manuscript fields`
`Warning: at xsl:stylesheet on line 7 column 40 of strip-spans.xsl: Running an XSLT 1 stylesheet with an XSLT 2 processor`
`Moving abouttheauthor before endofbook`
`Moving adcard before endofbook`
`Moving frontsales before endofbook`
`Moving toc before endofbook`
`Moving copyrightpage before endofbook`
`Addons to insert: []`
`SELECT * FROM vw_wf_title INNER JOIN vw_wf_person ON vw_wf_title.EDITION_ID = vw_wf_person.EDITION_ID WHERE EDITION_EAN LIKE '%9781466891005%' AND RELATIONSHIP_DESC = 'Author'`
`DB Connection SUCCESS: Found an author record`

**Comment by nelliemckesson** [comment]
@ericawarren I think this should be fixed. You should have the user run the file through again and verify before closing the issue. I revised the metadata handling to check for an ebook record if the print isbn does not have an associated record.

**Comment by nelliemckesson** [comment]
Oh also, the runheads didn't show up in the workflows_test path because I just haven't set up the runheads script for that path yet. But you can test in bookmaker_stg in the meantime.

**Comment by ericawarren** [comment]
User confirmed it's working correctly now.
