### ISSUE TITLE
If Author credit in Biblio is too long, verso running head runs over one line

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/bookmaker_addons#38]
For example, see attached (in picador_arc-serif), which has a Biblio author credit line as "Andrew Schulman; With an Afterword by Marvin A. McMillen, M.D."
[9781250055774_POD.pdf](https://github.com/macmillanpublishers/bookmaker_addons/files/41819/9781250055774_POD.pdf)

**Comment by nelliemckesson** [comment]
Added a snippet to the custom CSS confluence page, to replace the runhead text as needed.
