### ISSUE TITLE
Pulling outdated info from data warehouse and/or Biblio

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/bookmaker_addons#46]
For title THIS IS HOW IT ALWAYS IS (978-1-250-08855-0)

Previous title, THE ADVENTURES OF GRUMWALD AND PRINCESS STEPHANIE, was changed weeks ago but Bookmaker is pulling the old title into the recto running head. Sent css override file to EA to fix now, but we should check the Biblio -> data warehouse -> Bookmaker situation.

**Comment by nelliemckesson** [comment]
This should be resolved -- our data feed was migrated to the production feed.
