### ISSUE TITLE
auto-generated titlepage.jpg doesn't get overwritten when new file is run through

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/bookmaker_addons#61]
If there were errors in the auto-generated titlepage.jpg, running the .docx file through bookmaker again will just pick up the previous, incorrect titlepage instead of created a new one from the new manuscript. Cf. swerve_final/done/9781250118561 (the original MS did not have the title paragraph styled correctly so a blank titlepage.jpg was created. when the MS style was fixed and run through again, Bookmaker picked up the old titlepage.jpg)

**Comment by nelliemckesson** [comment]
Fixed. For older titles, titlepage will still need to be deleted manually once for the new code to kick in. Otherwise, titlepage will be re-generated with each conversion.
