### ISSUE TITLE
Add more graceful exit if ISBN lookup fails

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/bookmaker_addons#80]
Currently if `findSpecificISBN` function in `metadata_preprocessing.rb` doesn't find an ISBN, the script fails but Bookmaker continues, and produces PDF and EPUB files with no CSS applied. Would be more helpful to users if we could trap for this error and produce a more informative error message.

**Comment by nelliemckesson** [comment]
In this scenario, bookmaker should continue to run, and should use as much metadata from the manuscript as possible, and use the default css files.

**Comment by nelliemckesson** [comment]
Also ftr, Bookmaker used to fallback to manuscript data if no ISBN was found. I changed something when I adjusted the ISBN lookup functions that appears to have broken that fallback.

**Comment by mattretzer** [comment]
Submitted pull request for this:
https://github.com/macmillanpublishers/bookmaker_addons/pull/83
