### ISSUE TITLE
"copyright page features both the print and eBook versions of bulk purchase blurb"

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker_addons#85]
We are inserting the bulk purchase blurb for ebooks here:
https://github.com/macmillanpublishers/bookmaker_addons/blob/master/epubmaker_preprocessing.js#L29

But it appears many manuscripts may already contain an almost identical (print) version of the same blurb (see https://www.dropbox.com/s/8xl7ndy8szeagpb/9781250095213_EPUBfirstpass.epub?dl=0)

We should add a check & removal, or just update the blurb if it exists.

**Comment by mattretzer** [comment]
We found a title with a bulk purchase notice that did not match the existing one exactly..  reopening issue so we can consider making our match criteria more broad.
Wacky file here: https://macmillanpublishers.slack.com/files/erica.warren/F2P0A1ZV5/the_summer_of_owen_todd_setting_ms.docx

**Comment by nelliemckesson** [comment]
We might want to consider completely overwriting the copyright page for ebooks, replacing with an ebook-only template.

**Comment by mattretzer** [comment]
Resolved as per https://github.com/macmillanpublishers/bookmaker_addons/pull/106
