### ISSUE TITLE
ISBN lookup defaults to epub if 1st print is null

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/bookmaker_addons#88]
PDF created with EPUB ISBN even though there is a valid print ISBN, but there is also a record with no ISBN. Samples here:https://www.dropbox.com/sh/46yng5hekdybw19/AAABm9a6IRdSHPQ3fcm1ZayYa?dl=0

**Comment by mattretzer** [comment]
https://github.com/macmillanpublishers/bookmaker_addons/pull/89
Resolved!
